<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'Acerca de',
    'Are you sure you want to delete this item?' => '¿Seguro que desea eliminar este artículo?',
    'Back' => 'Volver',
    'Congratulations!' => 'Felicidades!',
    'Contact' => 'Contacto',
    'Create Status' => 'Crear estado',
    'Create a Post' => 'Después de crear un',
    'Created At' => 'Creado el',
    'Delete' => 'Eliminar',
    'Get started with Yii' => 'Empieza con Yii',
    'Heading' => 'La partida',
    'Home' => 'Inicio',
    'ID' => 'Id',
    'Logout(' => 'Salir (',
    'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.' => 'Ipsum de las zanahorias, las rebajas mejoradas, pero lo hacen occaecat tiempo y vitalidad, como el trabajo y la obesidad. Con los años, entraré, que nostrud aliquip fuera de ella la ventaja de ejercicio, por lo que los esfuerzos de estímulo si el distrito escolar y la longevidad. Cupidatat tarea si el consumidor quiere encontrar el placer del dolor que produce cillum hay fútbol vuelo resultante',
    'Menu' => 'Menú',
    'Message' => 'Mensaje',
    'Permissions' => 'Permiso',
    'Post Select2' => 'Después Seleccionar2',
    'Post has been updated.' => 'Post ha sido actualizada',
    'Posting' => 'El desplazamiento',
    'Reset' => 'Reset',
    'Save' => 'Guardar',
    'Search' => 'Busca',
    'Sign In' => 'Sign On',
    'Sign Up' => 'Regístrese',
    'Status' => 'Estado',
    'The requested page does not exist.' => 'La página solicitada no existe.',
    'Update' => 'Actualizar',
    'Update Status: {name}' => 'Actualización de estado: {nombre}',
    'Updated At' => 'Actualización a',
    'Yii Documentation' => 'Yu Documentación',
    'You have successfully created your Yii-powered application.' => 'Ha creado su aplicación con motor Yu.',
    'Yii Forum' => 'Foro de Yii',
    'Yii Extensions' => 'Extensiones Yii',
    'My Company' => 'Mi empresa',
    'Tags' => 'Etiquetas',
    'Post' => 'Enviar',
    'Verification Code' => 'código de verificación',
    'This is the About page. You may modify the following file to customize its content:' => 'Esta es la página Acerca de. Puede modificar el siguiente archivo para personalizar su contenido:',
    'About' => 'Acerca de',  
    '- Choose Permissions -' => '- Elija permisos -',
];
